from setuptools import setup, find_packages

setup(
    name="stock-analyzer",
    version="1.0.0",
    description="ระบบวิเคราะห์หุ้นแบบครบวงจร - Comprehensive Stock Analysis System",
    author="Stock Analysis Team",
    author_email="info@stockanalyzer.com",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.8",
    install_requires=[
        "pandas>=2.0.0",
        "numpy>=1.24.0",
        "scipy>=1.10.0",
        "requests>=2.31.0",
        "yfinance>=0.2.0",
        "alpha-vantage>=2.3.0",
        "finnhub-python>=2.4.0",
        "TA-Lib>=0.4.0",
        "pandas-ta>=0.3.0",
        "stockstats>=0.6.0",
        "scikit-learn>=1.3.0",
        "matplotlib>=3.7.0",
        "plotly>=5.15.0",
        "seaborn>=0.12.0",
        "mplfinance>=0.12.0",
        "flask>=2.3.0",
        "flask-cors>=4.0.0",
        "flask-socketio>=5.3.0",
        "sqlalchemy>=2.0.0",
        "python-dotenv>=1.0.0",
        "pyyaml>=6.0",
        "aiohttp>=3.8.0",
        "loguru>=0.7.0",
        "pytest>=7.4.0",
    ],
    extras_require={
        "ml": ["tensorflow>=2.13.0", "keras>=2.13.0"],
        "quant": ["quantlib>=1.31", "arch>=6.2.0"],
        "dev": ["black>=23.0.0", "flake8>=6.0.0", "mypy>=1.5.0"],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Financial and Insurance Industry",
        "Topic :: Office/Business :: Financial :: Investment",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    entry_points={
        "console_scripts": [
            "stock-analyzer=src.main:main",
        ],
    },
)